apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config-v2
data:
  kibana.yml: |
    ---
    # Default Kibana configuration from kibana-docker.
    server.name: kibana
    server.host: "0"
    elasticsearch.url: http://elasticsearch:9200
    elasticsearch.username: kibana
    elasticsearch.password: other!password
    xpack.monitoring.ui.container.elasticsearch.enabled: true
